"""empty message

Revision ID: 54388d22ef2d
Revises: f194c3dcd2e2
Create Date: 2021-03-16 16:13:52.775916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54388d22ef2d'
down_revision = 'f194c3dcd2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'address')
    # ### end Alembic commands ###
