"""empty message

Revision ID: f194c3dcd2e2
Revises: 
Create Date: 2021-03-16 15:58:37.197112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f194c3dcd2e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user_info', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='unique')
    op.drop_column('user_info', 'email')
    # ### end Alembic commands ###
